### ISSUE TITLE
Make userOrg configurable

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/kodein-internal-gradle-plugin#1]
It would be nice if [userOrg](https://github.com/Kodein-Framework/kodein-internal-gradle-plugin/blob/671853a515db9d9a215426e1d5058d609eb7c0b2/src/main/kotlin/org/kodein/internal/gradle/KodeinPublicationUpload.kt#L67) would be configurable so that we could upload to our own bintray repos if needed.

**Comment by SalomonBrys** [comment]
Fixed.
