### ISSUE TITLE
I need a js preset with IR only

### ISSUE THREAD

**Issue by dragossusi** [Kodein-Framework/kodein-internal-gradle-plugin#16]

**Comment by romainbsl** [comment]
Are you using our internal gradle plugin for your projects ?

**Comment by dragossusi** [comment]
So, the thing is, I was trying to use kodein with compose for web, tried to fork Kodein and add JS IR myself, but I couldn't find a way to do it.

**Comment by SalomonBrys** [comment]
Use internal-gradle-plugin 6.7.1
Set `org.kodein.js.useCompiler = ir` in gradle.properties.
