### ISSUE TITLE
Missing common main api publication in all kosi project

### ISSUE THREAD

**Issue by Prototik** [Kodein-Framework/kodein-internal-gradle-plugin#17]
I encounter following issue while using dokka:
```
Execution failed for task ':dokkaHtmlPartial'.
> Could not resolve all files for configuration ':metadataCompileClasspath'.
   > Could not resolve org.kodein.log:canard:0.14.0.
      > The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common'. However we cannot choose between the following variants of org.kodein.log:canard:0.14.0:
      ...
```

After some investigation It becomes clear: all projects who uses this plugin set missing `commonMainMetadataElements` in gradle module, which provides this artifact.

Let's compare module specifier from kotlinx-coroutines:
```
$ curl -s https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.6.3/kotlinx-coroutines-core-1.6.3.module | grep -A5 commonMainMetadataElements
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
$
```
And module from kodein-di:
```
$ curl -s https://repo1.maven.org/maven2/org/kodein/di/kodein-di/7.13.0/kodein-di-7.13.0.module | grep -A5 commonMainMetadataElements
$ // nothing
```

I assume it caused by some sort of host-only publication logic, provided by this plugin, which doesn't assign common publication to any host and it not published at all, but I'm not sure.

Without `commonMainMetadataElements` I cannot use dokka at all with any of kosi lib.

**Comment by romainbsl** [comment]
This has nothing to do with this plugin, but with Kotlin hierachical project structure. However there is an option to add the compatibility with non-hierachical project https://kotlinlang.org/docs/multiplatform-hierarchy.html#for-library-authors

Can you try with the latest snapshot of **Canard**?
repo: `https://s01.oss.sonatype.org/content/repositories/snapshots/`
version: `0.14.1-SNAPSHOT`

```
url -s https://s01.oss.sonatype.org/content/repositories/snapshots/org/kodein/log/canard/0.14.1-master-SNAPSHOT/canard-0.14.1-master-20220712.213747-1.module |  grep -A5 commonMainMetadataElements

"name": "commonMainMetadataElements",
"attributes": {
   "org.gradle.category": "library",
   "org.gradle.usage": "kotlin-api",
   "org.jetbrains.kotlin.platform.type": "common"
},
```
